steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/geo-dataset-backend', '.']
    dir: 'geo-dataset-backend'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/geo-dataset-backend']

  # Deploy to Cloud Run with secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-demo-app'
      - '--image=gcr.io/$PROJECT_ID/geo-dataset-backend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--set-secrets=MONGO_URI=MONGO_URI:latest'
      - '--allow-unauthenticated'
    secretEnv: ['MONGO_URI']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MONGO_URI/versions/latest
      env: 'MONGO_URI'

serviceAccount: '534281060187@cloudbuild.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
