steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-demo-app', '.']

  # Deploy to Cloud Run with secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-demo-app'
      - '--image=gcr.io/$PROJECT_ID/my-demo-app'
      - '--region=us-central1'
      - '--platform=managed'
      - '--set-secrets=MONGO_URI=demo-env-vars:latest'  # Syntax: ENV_VAR_NAME=SECRET_NAME:VERSION
      - '--allow-unauthenticated'
    secretEnv: ['MONGO_URI']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/demo-env-vars/versions/latest
      env: 'MONGO_URI'

serviceAccount: '534281060187@cloudbuild.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
