[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[build]
  publish = "dist"
  command = "npm run build"